language: node_js
node_js:
  - "5"
notifications:
  slack: ng-camp:aXB3psuLzMhyiqGoDglEu6Sv
  
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  
before_script:
  - cd frontend && npm install
  - sh -e /etc/init.d/xvfb start
  # - nohup bash -c webdriver-manager start 2>&1 & 
  - sleep 1  # give server time to start
  
branches:
  only: master

script: cd frontend && npm run test

cache:
  directories: node_modules
