ALTER TABLE hotel ALTER COLUMN description SET DATA TYPE TEXT;
ALTER TABLE mail_template ALTER COLUMN text SET DATA TYPE TEXT;
ALTER TABLE offer ALTER COLUMN description SET DATA TYPE TEXT;
ALTER TABLE offer_request ALTER COLUMN comment SET DATA TYPE TEXT;